backend:
  name: git-gateway
  branch: main

# Pasta onde os arquivos de mídia (imagens, vídeos, etc.) serão armazenados
media_folder: "assets/images/uploads"
# Caminho público para os arquivos de mídia
public_folder: "/assets/images/uploads"

collections:
  - name: "site_config"
    label: "Configuração do Site"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - { label: "Título do Hero", name: "hero_title", widget: "string", default: "Bem-vindo à La Navalha – Estilo, Rock e Tradição" }
          - { label: "Subtítulo do Hero", name: "hero_subtitle", widget: "text", default: "Transformando cortes de cabelo em uma experiência única." }
          - { label: "Link do Botão do Hero", name: "hero_button_link", widget: "string", default: "https://api.whatsapp.com/send/?phone=5555996238257" }
          - { label: "Texto do Botão do Hero", name: "hero_button_text", widget: "string", default: "Agendar Agora" }
          - { label: "Cor Primária", name: "primary_color", widget: "string", default: "#ffc107" }
          - { label: "Cor de Fundo", name: "background_color", widget: "string", default: "#000000" }
          - { label: "Cor do Texto", name: "text_color", widget: "string", default: "#ffffff" }
      - label: "Menu"
        name: "menu"
        file: "content/menu.json"
        fields:
          - { label: "Texto do Link Home", name: "menu_home", widget: "string", default: "Home" }
          - { label: "Texto do Link FAQ", name: "menu_faq", widget: "string", default: "Dúvidas" }
          - { label: "Texto do Link Cosméticos", name: "menu_cosmeticos", widget: "string", default: "Cosméticos" }
          - { label: "Link do Botão WhatsApp do Menu", name: "menu_whatsapp", widget: "string", default: "https://api.whatsapp.com/send/?phone=5555996238257" }
      - label: "Rodapé"
        name: "footer"
        file: "content/footer.json"
        fields:
          - { label: "Texto do Rodapé", name: "footer_text", widget: "string", default: "© 2025 La Navalha. Todos os direitos reservados." }
  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título da Página", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
