backend:
  name: github
  repo: lukeshaye/netlifycms-teste


# Pasta onde as mídias serão salvas (imagens, vídeos etc.)
media_folder: "assets/images"
# Caminho público para as mídias (como elas serão referenciadas no site)
public_folder: "/assets/images"

collections:
  - name: "site_config"
    label: "Configuração do Site"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }
