backend:
  name: git-gateway
  branch: main # ou master, dependendo da branch principal do seu repositório

media_folder: "assets/images" # Pasta onde as imagens serão armazenadas
public_folder: "/assets/images" # URL pública para as imagens

collections:
  - name: "config"
    label: "Configurações do Site"
    files:
      - name: "general"
        label: "Configurações Gerais"
        file: "site_config.json"
        format: "json"
        fields:
          - {label: "Título da Aba", name: "titulo_aba_navegacao", widget: "string"}
          - {label: "Cor Primária", name: "primary_color", widget: "color", default: "#020202"}
          - {label: "Cor Secundária", name: "secondary_color", widget: "color", default: "#EFEB5F"}
          - {label: "Cor de Destaque", name: "accent_color", widget: "color", default: "#BE1E31"}
          
          # Menu
          - {label: "Texto do Menu - Home", name: "menu_item1_text", widget: "string"}
          - {label: "Texto do Menu - Dúvidas", name: "menu_item2_text", widget: "string"}
          - {label: "Texto do Menu - Endereço", name: "menu_item3_text", widget: "string"}
          
          # Links
          - {label: "Link do Facebook", name: "facebook", widget: "string"}
          - {label: "Link do Instagram", name: "instagram", widget: "string"}
          - {label: "Link do WhatsApp", name: "telefone_menu", widget: "string"}
          
          # Hero Section
          - {label: "Título Principal", name: "hero_title", widget: "string"}
          - {label: "Subtítulo", name: "hero_subtitle", widget: "string"}
          - {label: "Texto do Botão", name: "hero_button_text", widget: "string"}
          
          # Testimonials
          - {label: "Depoimento 1 - Texto", name: "testimonial1_text", widget: "text"}
          - {label: "Depoimento 1 - Nome", name: "testimonial1_name", widget: "string"}
          - {label: "Depoimento 2 - Texto", name: "testimonial2_text", widget: "text"}
          - {label: "Depoimento 2 - Nome", name: "testimonial2_name", widget: "string"}
          - {label: "Depoimento 3 - Texto", name: "testimonial3_text", widget: "text"}
          - {label: "Depoimento 3 - Nome", name: "testimonial3_name", widget: "string"}
          
          # Metrics
          - {label: "Métrica 1", name: "metric1_text", widget: "string"}
          - {label: "Métrica 2", name: "metric2_text", widget: "string"}
          - {label: "Métrica 3", name: "metric3_text", widget: "string"}
          
          # CTA
          - {label: "Texto do Botão Agendar", name: "botao_agendar_text", widget: "string"}
          - {label: "Link do Botão Agendar", name: "botao_agendar_link", widget: "string"}
          
          # Contato
          - {label: "Endereço", name: "contact_address", widget: "text"}
          - {label: "Horário de Funcionamento", name: "contact_hours", widget: "text"}
          
          # FAQ
          - {label: "Pergunta 1", name: "faq1_question", widget: "string"}
          - {label: "Resposta 1", name: "faq1_answer", widget: "text"}
          - {label: "Pergunta 2", name: "faq2_question", widget: "string"}
          - {label: "Resposta 2", name: "faq2_answer", widget: "text"}
          - {label: "Pergunta 3", name: "faq3_question", widget: "string"}
          - {label: "Resposta 3", name: "faq3_answer", widget: "text"}
          
          # Footer
          - {label: "Texto do Rodapé", name: "footer_text", widget: "string"}