backend:
  name: git-gateway
  branch: main # ou master, dependendo da branch principal do seu repositório

media_folder: "assets/images" # Pasta para upload de imagens
public_folder: "/assets/images" # URL pública para as imagens

collections:
  - name: "config"
    label: "Configurações do Site"
    files:
      - name: "general"
        label: "Configurações Gerais"
        file: "site_config.json"
        format: "json"
        fields:
          - {label: "Título da Aba", name: "titulo_aba_navegacao", widget: "string", default: "Barbearia Entre Amigos - São Borja/RS"}
          
          # Cores Principais
          - {label: "Cor Primária", name: "primary_color", widget: "color", default: "#020202"}
          - {label: "Cor Secundária", name: "secondary_color", widget: "color", default: "#EFEB5F"}
          - {label: "Cor de Destaque", name: "accent_color", widget: "color", default: "#BE1E31"}
          - {label: "Cor do Texto", name: "text_color", widget: "color", default: "#000000"}
          - {label: "Cor dos Links", name: "link_color", widget: "color", default: "#BE1E31"}
          - {label: "Cor de Fundo", name: "background_color", widget: "color", default: "#ffffff"}
          - {label: "Cor de Fundo do Corpo", name: "body_background", widget: "color", default: "#ffffff"}
          
          # Menu
          - label: "Menu"
            name: "menu_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo do Menu", name: "menu_background", widget: "color", default: "rgba(2, 2, 2, 0.9)"}
              - {label: "Cor dos Três Pontinhos", name: "tres_pontinhos_cor", widget: "string", default: "color: #EFEB5F;"}
              - {label: "Texto do Menu - Home", name: "menu_item1_text", widget: "string", default: "Home"}
              - {label: "Link do Menu - Home", name: "menu_item1_link", widget: "string", default: "index.html"}
              - {label: "Cor do Menu - Home", name: "menu_item1_color", widget: "color", default: "#EFEB5F"}
              - {label: "Texto do Menu - Dúvidas", name: "menu_item2_text", widget: "string", default: "Dúvidas"}
              - {label: "Link do Menu - Dúvidas", name: "menu_item2_link", widget: "string", default: "index.html#faq-1-uDfHrio6NM"}
              - {label: "Cor do Menu - Dúvidas", name: "menu_item2_color", widget: "color", default: "#EFEB5F"}
              - {label: "Texto do Menu - Endereço", name: "menu_item3_text", widget: "string", default: "Endereço"}
              - {label: "Link do Menu - Endereço", name: "menu_item3_link", widget: "string", default: "index.html#contacts-2-uDfHrio4Yq"}
              - {label: "Cor do Menu - Endereço", name: "menu_item3_color", widget: "color", default: "#EFEB5F"}
              - {label: "Link do WhatsApp", name: "telefone_menu", widget: "string", default: "https://api.whatsapp.com/message/AV63A6D6IH6JC1?autoload=1&app_absent=0"}
              - {label: "Cor do Ícone do WhatsApp", name: "phone_icon_color", widget: "color", default: "#EFEB5F"}
              - {label: "Link do Facebook", name: "facebook", widget: "string", default: "https://www.facebook.com/isaaccarpesbarbeiro/"}
              - {label: "Cor do Ícone do Facebook", name: "facebook_icon_color", widget: "color", default: "#EFEB5F"}
              - {label: "Link do Instagram", name: "instagram", widget: "string", default: "https://www.instagram.com/barbeariaentreamigos1/"}
              - {label: "Cor do Ícone do Instagram", name: "instagram_icon_color", widget: "color", default: "#EFEB5F"}
              - {label: "Cor de Fundo do Botão Menu", name: "botao_menu_bg", widget: "string", default: "transparent"}
              - {label: "Cor do Botão Menu", name: "botao_menu_color", widget: "color", default: "#BE1E31"}
              - {label: "Cor da Borda do Botão Menu", name: "botao_menu_border", widget: "color", default: "#BE1E31"}
              - {label: "Link do Botão Menu", name: "botao_menu", widget: "string", default: "https://api.whatsapp.com/message/AV63A6D6IH6JC1?autoload=1&app_absent=0"}
              - {label: "Texto do Botão Menu", name: "texto_botao_menu", widget: "string", default: "Whatsapp"}
          
          # Banner/Hero
          - label: "Banner Principal"
            name: "hero_section"
            widget: "object"
            fields:
              - {label: "Opacidade do Overlay", name: "hero_overlay_opacity", widget: "string", default: "0.6"}
              - {label: "Cor do Overlay", name: "hero_overlay_color", widget: "string", default: "rgb(2, 2, 2)"}
              - {label: "Título do Banner", name: "hero_title", widget: "string", default: "Barbearia Entre Amigos - Estilo e tradição"}
              - {label: "Cor do Título", name: "hero_title_color", widget: "color", default: "#EFEB5F"}
              - {label: "Subtítulo do Banner", name: "hero_subtitle", widget: "string", default: "Cortes modernos e atendimento personalizado"}
              - {label: "Cor do Subtítulo", name: "hero_subtitle_color", widget: "color", default: "#ffffff"}
              - {label: "Texto do Botão", name: "hero_button_text", widget: "string", default: "Agendar Agora"}
              - {label: "Cor do Botão", name: "hero_button_color", widget: "color", default: "#BE1E31"}
              - {label: "Cor da Borda do Botão", name: "hero_button_border", widget: "color", default: "#BE1E31"}
              - {label: "Link do Botão", name: "hero_button_link", widget: "string", default: "https://api.whatsapp.com/message/AV63A6D6IH6JC1?autoload=1&app_absent=0"}
          
          # Avaliações
          - label: "Avaliações"
            name: "testimonials_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "testimonials_bg", widget: "color", default: "#ffffff"}
              - {label: "Título da Seção", name: "testimonials_title", widget: "string", default: "Avaliações"}
              - {label: "Cor do Título", name: "testimonials_title_color", widget: "color", default: "#020202"}
              
              - {label: "Fundo do Depoimento 1", name: "testimonial1_bg", widget: "color", default: "#f9f9f9"}
              - {label: "Texto do Depoimento 1", name: "testimonial1_text", widget: "text", default: "Atendimento top, corte perfeito, preço acessível ... recomendo!!!"}
              - {label: "Cor do Texto 1", name: "testimonial1_text_color", widget: "color", default: "#020202"}
              - {label: "Nome do Cliente 1", name: "testimonial1_name", widget: "string", default: "Andréia Franke"}
              - {label: "Cor do Nome 1", name: "testimonial1_name_color", widget: "color", default: "#BE1E31"}
              
              - {label: "Fundo do Depoimento 2", name: "testimonial2_bg", widget: "color", default: "#f9f9f9"}
              - {label: "Texto do Depoimento 2", name: "testimonial2_text", widget: "text", default: "Excelente atendimento, ótimo trabalho, ambiente muito agradável. Recomendo!"}
              - {label: "Cor do Texto 2", name: "testimonial2_text_color", widget: "color", default: "#020202"}
              - {label: "Nome do Cliente 2", name: "testimonial2_name", widget: "string", default: "Cliente Satisfeito"}
              - {label: "Cor do Nome 2", name: "testimonial2_name_color", widget: "color", default: "#BE1E31"}
              
              - {label: "Fundo do Depoimento 3", name: "testimonial3_bg", widget: "color", default: "#f9f9f9"}
              - {label: "Texto do Depoimento 3", name: "testimonial3_text", widget: "text", default: "Profissionais qualificados, ambiente agradável e preço justo. Melhor barbearia da cidade!"}
              - {label: "Cor do Texto 3", name: "testimonial3_text_color", widget: "color", default: "#020202"}
              - {label: "Nome do Cliente 3", name: "testimonial3_name", widget: "string", default: "Cliente Fiel"}
              - {label: "Cor do Nome 3", name: "testimonial3_name_color", widget: "color", default: "#BE1E31"}
          
          # Métricas
          - label: "Métricas"
            name: "metrics_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "metrics_bg", widget: "color", default: "#ffffff"}
              
              - {label: "Texto da Métrica 1", name: "metric1_text", widget: "string", default: "Mais de 7 anos no mercado"}
              - {label: "Cor do Texto 1", name: "metric1_text_color", widget: "color", default: "#020202"}
              - {label: "Cor do Ícone 1", name: "metric1_icon_color", widget: "color", default: "#BE1E31"}
              
              - {label: "Texto da Métrica 2", name: "metric2_text", widget: "string", default: "Serviços variados para todos os gostos"}
              - {label: "Cor do Texto 2", name: "metric2_text_color", widget: "color", default: "#020202"}
              - {label: "Cor do Ícone 2", name: "metric2_icon_color", widget: "color", default: "#BE1E31"}
              
              - {label: "Texto da Métrica 3", name: "metric3_text", widget: "string", default: "Profissionais altamente qualificados"}
              - {label: "Cor do Texto 3", name: "metric3_text_color", widget: "color", default: "#020202"}
              - {label: "Cor do Ícone 3", name: "metric3_icon_color", widget: "color", default: "#BE1E31"}
          
          # Botão CTA
          - label: "Botão Agendar"
            name: "cta_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "cta_section_bg", widget: "color", default: "#020202"}
              - {label: "Texto do Botão", name: "botao_agendar_text", widget: "string", default: "Agendar Agora"}
              - {label: "Link do Botão", name: "botao_agendar_link", widget: "string", default: "https://api.whatsapp.com/message/AV63A6D6IH6JC1?autoload=1&app_absent=0"}
              - {label: "Cor do Botão", name: "botao_agendar_bg", widget: "color", default: "#BE1E31"}
              - {label: "Cor do Texto do Botão", name: "botao_agendar_text_color", widget: "color", default: "#ffffff"}
              - {label: "Cor do Hover", name: "botao_agendar_hover", widget: "color", default: "#d01c2d"}
              - {label: "Arredondamento do Botão", name: "botao_agendar_radius", widget: "string", default: "50px"}
              - {label: "Espaçamento Interno", name: "botao_agendar_padding", widget: "string", default: "15px 30px"}
              - {label: "Tamanho da Fonte", name: "botao_agendar_font_size", widget: "string", default: "1.2rem"}
          
          # Contato
          - label: "Contato"
            name: "contacts_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "contacts_bg", widget: "color", default: "#ffffff"}
              - {label: "Título da Seção", name: "contacts_title", widget: "string", default: "Contato"}
              - {label: "Cor do Título", name: "contacts_title_color", widget: "color", default: "#020202"}
              - {label: "Cor dos Textos", name: "contacts_text_color", widget: "color", default: "#020202"}
              
              - {label: "Rótulo do Telefone", name: "contact_phone_label", widget: "string", default: "WhatsApp:"}
              - {label: "Número de Telefone", name: "contact_phone", widget: "string", default: "Clique no ícone acima"}
              - {label: "Rótulo do WhatsApp", name: "contact_whatsapp_label", widget: "string", default: "WhatsApp:"}
              - {label: "Número do WhatsApp", name: "contact_whatsapp", widget: "string", default: "Clique no ícone acima"}
              - {label: "Rótulo do Endereço", name: "contact_address_label", widget: "string", default: "Endereço:"}
              - {label: "Endereço", name: "contact_address", widget: "text", default: "R. Borges do Canto, 660 - Tiro, São Borja - RS, 97670-000"}
              - {label: "Rótulo do Horário", name: "contact_hours_label", widget: "string", default: "Horário de Funcionamento:"}
              - {label: "Horário", name: "contact_hours", widget: "text", default: "Segunda a Sexta: 9h - 19h | Sábado: 9h - 17h | Domingo: Fechado"}
              
              - {label: "Iframe do Google Maps", name: "google_maps_embed", widget: "text", default: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3462.5!2d-56.0!3d-28.6!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94790b3b8b3b3b3b%3A0x3b3b3b3b3b3b3b3b!2sR.%20Borges%20do%20Canto%2C%20660%20-%20Tiro%2C%20S%C3%A3o%20Borja%20-%20RS%2C%2097670-000!5e0!3m2!1spt-BR!2sbr!4v1741181169652!5m2!1spt-BR!2sbr"}
          
          # Redes Sociais
          - label: "Redes Sociais"
            name: "social_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "social_bg", widget: "color", default: "#ffffff"}
              - {label: "Link do Facebook", name: "facebook_link", widget: "string", default: "https://www.facebook.com/isaaccarpesbarbeiro/"}
              - {label: "Cor de Fundo do Facebook", name: "facebook_bg", widget: "color", default: "#020202"}
              - {label: "Cor do Ícone do Facebook", name: "facebook_icon_color", widget: "color", default: "#ffffff"}
              - {label: "Link do Instagram", name: "instagram_link", widget: "string", default: "https://www.instagram.com/barbeariaentreamigos1/"}
              - {label: "Cor de Fundo do Instagram", name: "instagram_bg", widget: "color", default: "#020202"}
              - {label: "Cor do Ícone do Instagram", name: "instagram_icon_color", widget: "color", default: "#ffffff"}
          
          # FAQ
          - label: "Perguntas Frequentes"
            name: "faq_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo da Seção", name: "faq_bg", widget: "color", default: "#ffffff"}
              - {label: "Título da Seção", name: "faq_title", widget: "string", default: "Perguntas Frequentes"}
              - {label: "Cor do Título", name: "faq_title_color", widget: "color", default: "#020202"}
              
              - {label: "Pergunta 1", name: "faq1_question", widget: "string", default: "Quais serviços vocês oferecem?"}
              - {label: "Cor da Pergunta 1", name: "faq1_question_color", widget: "color", default: "#020202"}
              - {label: "Resposta 1", name: "faq1_answer", widget: "text", default: "Corte de cabelo, barba, sobrancelha, tratamentos capilares e muito mais. Consulte nossos profissionais para mais detalhes."}
              - {label: "Cor da Resposta 1", name: "faq1_answer_color", widget: "color", default: "#020202"}
              
              - {label: "Pergunta 2", name: "faq2_question", widget: "string", default: "Preciso agendar horário?"}
              - {label: "Cor da Pergunta 2", name: "faq2_question_color", widget: "color", default: "#020202"}
              - {label: "Resposta 2", name: "faq2_answer", widget: "text", default: "Recomendamos o agendamento prévio para garantir seu atendimento sem espera. Entre em contato pelo WhatsApp para agendar seu horário."}
              - {label: "Cor da Resposta 2", name: "faq2_answer_color", widget: "color", default: "#020202"}
              
              - {label: "Pergunta 3", name: "faq3_question", widget: "string", default: "Qual o horário de funcionamento?"}
              - {label: "Cor da Pergunta 3", name: "faq3_question_color", widget: "color", default: "#020202"}
              - {label: "Resposta 3", name: "faq3_answer", widget: "text", default: "Segunda a Sexta: 09:00 - 19:00 | Sábado: 09:00 - 17:00 | Domingo: Fechado"}
              - {label: "Cor da Resposta 3", name: "faq3_answer_color", widget: "color", default: "#020202"}
          
          # Rodapé
          - label: "Rodapé"
            name: "footer_section"
            widget: "object"
            fields:
              - {label: "Cor de Fundo do Rodapé", name: "footer_bg", widget: "color", default: "#020202"}
              - {label: "Texto do Rodapé", name: "footer_text", widget: "string", default: "2025 Barbearia Entre Amigos. Todos os direitos reservados."}
              - {label: "Cor do Texto do Rodapé", name: "footer_text_color", widget: "color", default: "#EFEB5F"}