---
{
  "titulo_aba_navegacao": "Barbearia La Max - São Borja/RS",
  "cores": {
    "primary_color": "#020202",
    "secondary_color": "#EFEB5F",
    "accent_color": "#BE1E31",
    "text_color": "#020202",
    "link_color": "#BE1E31",
    "background_color": "#ffffff",
    "menu_background": "rgba(2, 2, 2, 0.9)",
    "footer_background": "#020202",
    "body_background": "#ffffff"
  },
  "menu": {
    "menu_style": "background-color: rgba(2, 2, 2, 0.9);",
    "tres_pontinhos_cor": "color: #EFEB5F;",
    "home_link": "index.html",
    "logo_image": "assets/images/1.jpg",
    "logo_alt": "Barbearia La Max",
    "logo_height": "5rem",
    "item1": {
      "menu_item1_text": "Home",
      "menu_item1_link": "index.html",
      "menu_item1_color": "#EFEB5F"
    },
    "item2": {
      "menu_item2_text": "Dúvidas",
      "menu_item2_link": "index.html#faq-1-uDfHrio6NM",
      "menu_item2_color": "#EFEB5F"
    },
    "item3": {
      "menu_item3_text": "Endereço",
      "menu_item3_link": "index.html#contacts-2-uDfHrio4Yq",
      "menu_item3_color": "#EFEB5F"
    },
    "social_links": {
      "telefone_menu": "Giuseppepicamole.com",
      "facebook": "Giuseppepicamole.com",
      "instagram": "caludovario,com",
      "phone_icon_color": "color: #EFEB5F;",
      "facebook_icon_color": "color: #EFEB5F;",
      "instagram_icon_color": "color: #EFEB5F;"
    },
    "botao": {
      "botao_menu": "Giuseppepicamole.com",
      "texto_botao_menu": "Whatsapp",
      "botao_menu_bg": "transparent",
      "botao_menu_color": "#BE1E31",
      "botao_menu_border": "#BE1E31"
    }
  },
  "hero": {
    "hero_overlay_opacity": "0.6",
    "hero_overlay_color": "rgb(2, 2, 2)",
    "hero_title": "Barbearia La Max - Cuidando de você com qualidade",
    "hero_title_color": "#EFEB5F",
    "hero_subtitle": "Cortes modernos e atendimento personalizado",
    "hero_subtitle_color": "#ffffff",
    "hero_button_text": "Agendar Agora",
    "hero_button_link": "Giuseppepicamole.com",
    "hero_button_color": "#BE1E31",
    "hero_button_border": "#BE1E31"
  },
  "testimonials": {
    "testimonials_bg": "#ffffff",
    "testimonials_title": "Avaliações",
    "testimonials_title_color": "#020202",
    "testimonial1": {
      "testimonial1_bg": "#f9f9f9",
      "testimonial1_text": "Amei ficou lindo, recomendo a todos",
      "testimonial1_text_color": "#020202",
      "testimonial1_name": "Marcos Gomes",
      "testimonial1_name_color": "#BE1E31"
    },
    "testimonial2": {
      "testimonial2_bg": "#f9f9f9",
      "testimonial2_text": "Adorei o atendimento, super recomendo",
      "testimonial2_text_color": "#020202",
      "testimonial2_name": "Neiva Silva",
      "testimonial2_name_color": "#BE1E31"
    },
    "testimonial3": {
      "testimonial3_bg": "#f9f9f9",
      "testimonial3_text": "mantendo a qualidade, sempre",
      "testimonial3_text_color": "#020202",
      "testimonial3_name": "Roberto Arantes",
      "testimonial3_name_color": "#BE1E31"
    }
  },
  "parallax": {
    "parallax_overlay_opacity": "0.5",
    "parallax_overlay_color": "rgb(2, 2, 2)"
  },
  "metrics": {
    "metrics_bg": "#ffffff",
    "metric1": {
      "metric1_text": "Temos um cacto bonito",
      "metric1_text_color": "#020202",
      "metric1_icon_color": "#BE1E31"
    },
    "metric2": {
      "metric2_text": "Agora atendemos gatos barbudos",
      "metric2_text_color": "#020202",
      "metric2_icon_color": "#BE1E31"
    },
    "metric3": {
      "metric3_text": "Bora coratar esses cabelo",
      "metric3_text_color": "#020202",
      "metric3_icon_color": "#BE1E31"
    }
  },
  "cta": {
    "cta_section_bg": "#020202",
    "botao_agendar_text": "Agendar Agora",
    "botao_agendar_link": "Giuseppepicamole.com",
    "botao_agendar_bg": "#BE1E31",
    "botao_agendar_text_color": "#ffffff",
    "botao_agendar_radius": "50px",